DjangoDemo/urls.py
from django.contrib import admin
from django.conf.urls import include, url

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include(('DjangoDemos.urls', 'DjangoDemos'), namespace='DjangoDemos')),
    url(r'^users/', include(('users.urls','users'), namespace='users')),
]

DjangoDemos/urls.py
# -*- coding: utf-8 -*-
"""定义DjangoDemos的URL模式"""

from django.conf.urls import url
from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),

    # 显示所有主题
    url(r'^topics/$', views.topics, name='topics'),

    # 显示特定的主题页
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),

    #显示新的主题主页
    url(r'^new_topic/$', views.new_topic, name='new_topic'),

#     用于添加新条目的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),

    # 编辑条目
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),

    url(r'^delete_entry/(?P<entry_id>\d+)/$', views.delete_entry, name='delete_entry'),

    url(r'^delete_topic/(?P<topic_id>\d+)/$', views.delete_topic, name='delete_topic')
]

users/urls.py
# -*- coding: utf-8 -*-

"""为应用程序users定义url模式"""
from django.conf.urls import url
from django.contrib.auth.views import LoginView


from . import views

urlpatterns = [
    # 登陆界面
    url(r'^login/$', LoginView.as_view(template_name='users/login.html'), name='login'),

    # 注销用户
    url(r'^logout/$', views.logout_view, name='logout'),

    # 注册界面
    url(r'^register/$', views.register, name='register'),
]

DjangoDemos/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Topic(models.Model):
    """用户学习主题"""
    text = models.CharField(max_length=200)
    data_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """学到有关某个主题的具体知识"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)  # 外键关联到指定主题
    text = models.TextField() # 不限制文字长度
    date_added = models.DateTimeField(auto_now_add=True) # 按照创建顺序呈现条目，并在每个条目旁放置时间戳

    class Meta: # 我们在实体类中嵌套了Meta类储存管理模型的额外信息使用entries返回多个条目
        verbose_name_plural = 'entries'


    def __str__(self):
        """返回模型字符串表示"""
        return self.text[:50] + "..."

users/models.py
from django.db import models

# Create your models here.

DjangoDemos/views.py
from django.shortcuts import render
from .models import Topic, Entry
from django.urls import reverse
from django.http import  HttpResponseRedirect
from .form import TopicForm
from .form import EntryForm
from django.contrib.auth.decorators import login_required
from django.http import Http404


def index(request):
    """学习笔记的主页"""
    return render(request, 'DjangoDemos/index.html')


@login_required
def topics(request):
    """显示所有主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('data_added') # 用户只能看到自己的主题
    # topics = Topic.objects.order_by('data_added')
    context = {'topics':topics}
    return render(request, 'DjangoDemos/topics.html', context)

@login_required
def topic(request, topic_id):
    """显示单个主题及其所有条目"""
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic, 'entries':entries}
    return render(request, 'DjangoDemos/topic.html', context)

@login_required
def new_topic(request):
    """添加新的主题"""
    if request.method != 'POST': # 测试确定请求是 POST还是GET,GET方法返回一个空表单

         """未提交数据：创建一个新表单"""
         form = TopicForm() # 创建一个TopicForm， 由于TopicForm没有指定任何参数，Django将创建一个空表单
    else:
        """POST提交数据：创建一个新表单"""
        form =  TopicForm(request.POST) # POST的数据存储request.POST
        if form.is_valid(): # 要将提交的信息保存到数据库，必须先通过确定他们是有效的， is_valid核实用户填写了所有必不可少的字段
            new_topic = form.save(commit=False) # 将表单数据写入数据库
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('DjangoDemos:topics'))# 使用reverse()获取页面topics的url, 并将它传递给HttpResponseRedirect(重定向到页面topics)

    context = {'form': form} # 将变量存储在formz中，并通过上下文字典
    return render(request, 'DjangoDemos/new_topic.html', context)

    context = {'form': form} # 将变量存储在formz中，并通过上下文字典


@login_required
def delete_topic(request, topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    else:
        topic.delete()
        return HttpResponseRedirect(reverse('DjangoDemos:topics'))

@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)


    if request.method != 'POST':
        '''未提交数据'''
        form = EntryForm()
    else:
        '''POST提交数据，对数据进行处理'''
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('DjangoDemos:topic', args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'DjangoDemos/new_entry.html', context)


@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    else:
        entry.delete()
        return HttpResponseRedirect(reverse('DjangoDemos:topic', args=[topic.id]))



@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # 初次请求，使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        #POST提交的数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('DjangoDemos:topic',args=[topic.id]))
    context = {'entry':entry, 'topic':topic, 'form':form}
    return render(request,'DjangoDemos/edit_entry.html', context)

users/views.py
from django.shortcuts import render

# Create your views here.

from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import logout
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('DjangoDemos:index'))# 登出后重定向到主页

def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册信息
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # 让用户自动登陆，再重定向到主页
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('DjangoDemos:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

DjangoDemos/templates/DjangoDemos/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Learning Log</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}

  </head>

  <body>

    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">

        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'DjangoDemos:index' %}">
              Learning Log</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'DjangoDemos:topics' %}">Topics</a></li>
          </ul>

          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->

      </div>
    </nav>

    <div class="container">

      <div class="page-header">
        {% block header %}{% endblock %}
      </div>
      <div>
        {% block content %}{% endblock %}
      </div>

    </div> <!-- /container -->

  </body>
</html>

DjangoDemos/templates/DjangoDemos/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "DjangoDemos/base.html" %}
{% block content %}
    <p><a href="{% url  'DjangoDemos:topic' topic.id %}">{{ topic }}</a> </p>
    <p>Edit entry:</p>

    <form action="{% url 'DjangoDemos:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
    </form>
{% endblock content %}
</body>
</html>

DjangoDemos/templates/DjangoDemos/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends "DjangoDemos/base.html" %}
{% block header %}
    <div class="jumbotron">
    <h1>Track your learning.</h1>
    </div>
{% endblock header %}
{% block content %}
    <h2>
    <a href="{% url 'users:register' %}">Register an account</a> to make your own Learning Log, and list the topics  you're learning about.
    </h2>
    <h2>
    Whatever you learn something new about a topic ,make an entry summarizing what you've learned.
    </h2>

{%  endblock content %}
</body>
</html>

DjangoDemos/templates/DjangoDemos/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#继承base.html#}
{% extends "DjangoDemos/base.html"%}
{% block  content %}
    <p><a href="{% url 'DjangoDemos:topic' topic.id %}">{{ topic }}</a> </p>
    <p>Add a new entry:</p>
    <form action="{%  url 'DjangoDemos:new_entry' topic.id %}" method="post">
    {# 防止攻击者利用表单来获得对服务器未经授权的访问   #}
        {%  csrf_token %}
    {#使用DJango创建表单只需包含变量as_p让Django以段落的格式渲染所有表单元素    #}
        {{ form.as_p }}
{#Django不会为表单创建按钮，所以自行创建#}
    <button name="submit">add entry</button>
    </form>
{% endblock content %}
</body>
</html>

DjangoDemos/templates/DjangoDemos/new_topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{#继承base.html#}
{% extends "DjangoDemos/base.html"%}
{% load bootstrap3 %}
{% block  header %}
    <h2>Add a new topic:</h2>
{% endblock header %}
{% block content %}
    <form action="{%  url 'DjangoDemos:new_topic' %}" method="post" class="form">
    {# 防止攻击者利用表单来获得对服务器未经授权的访问   #}
        {%  csrf_token %}
    {#使用DJango创建表单只需包含变量as_p让Django以段落的格式渲染所有表单元素    #}
{#        {{ form.as_p }}#}
        {% bootstrap_form form %}
{#Django不会为表单创建按钮，所以自行创建#}
        {% buttons %}
    <button name="submit">add topic</button>
    {% endbuttons %}
    </form>
{% endblock content %}
</body>
</html>

DjangoDemos/templates/DjangoDemos/topic.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% extends 'DjangoDemos/base.html' %}
{% block header %}
    <h2>{{ topic }}</h2>
     <small>
         <a href="{% url 'DjangoDemos:delete_topic' topic.id %}">delete topic</a>
     </small>
{% endblock header%}
{% block content %}
    <p>
    <a href="{% url 'DjangoDemos:new_entry' topic.id %}">add a new entry</a>
    </p>
    {% for entry in entries %}
      <div class="panel panel-default">
      <div class="panel-heading">
          <h3>
              {{ entry.date_added|date:'M d, Y H:i' }}
              <small>
                  <a href="{% url 'DjangoDemos:edit_entry' entry.id %}">edit entry</a>
              </small>
              <small>
                  <a href="{% url 'DjangoDemos:delete_entry' entry.id %}">delete entry</a>
              </small>
          </h3>
      </div>
      <div class="panel-body">
          {{ entry.text|linebreaks }}
      </div>
      </div>
    {% empty %}
        There are no entries for this topic yet.
    {% endfor %}
    </ul>
{% endblock %}
</body>
</html>

DjangoDemos/templates/DjangoDemos/topics.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<h3>
{% extends "DjangoDemos/base.html" %}
{% block header %}
    <h1>Topics</h1>
{% endblock header %}
{% block content %}
<ul>
    {% for topic in topics%}
    <li>
        <h3><a href="{%  url 'DjangoDemos:topic' topic.id%}">{{ topic }}</a></h3>

    </li>
    {%empty%}
    <li>No topics have been added yet.</li>
    {%endfor%}
</ul>
    <h3><a href="{% url 'DjangoDemos:new_topic' %}">Add a new topic</a></h3>
{% endblock content %}
</body>
</html>

users/templates/users/login.html
{% extends "DjangoDemos/base.html" %}

{% block content %}

  {% if form.errors %}
  <p>Your username and password didn't match. Please try again.</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}">
  {% csrf_token %}
  {{ form.as_p }}

  <button name="submit">log in</button>
  <input type="hidden" name="next" value="{% url 'DjangoDemos:index' %}" />
  </form>
    
{% endblock content %}

users/templates/users/register.html
{% extends "DjangoDemos/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">register</button>
    <input type="hidden" name="next" value="{% url 'DjangoDemos:index' %}" />
  </form>
    
{% endblock content %}